version: "3"
services:
  dev-environment:
    build: .
    container_name: student-dev
    tty: true
    privileged: true
    ports:
      - "8080:8080"  # VS Code Server
      - "8888:8888"  # JupyterLab
    volumes:
      - ./workspace:/home/student/workspace
    networks:
      devnet:
        ipv4_address: 10.10.10.10

  # Optional: Uncomment if you need additional containers for networking exercises
  # target-system:
  #   build: .
  #   container_name: target
  #   tty: true
  #   privileged: true
  #   networks:
  #     devnet:
  #       ipv4_address: 10.10.10.11

networks:
  devnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24